# Generated by Django 4.2 on 2025-06-27 07:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenShop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('sku', models.TextField()),
                ('description', models.TextField()),
                ('shop', models.TextField()),
                ('location', models.TextField()),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('category', models.TextField()),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('picture', models.TextField()),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
